language: generic
os: osx
sudo: required
dist: trusty
osx_image: xcode9.3

env:
  global:
    secure: lcb1Oi27It6qinDgWWO5+G2cetc/0achAGTG7H6SqeV0+bRRLvYUXvyDFAkE/BVSBC3xsxHWYvwPrx8j9AcXdhaIOLgeqBF3fGCKMilzd2E6Pt4o/zjfWtdINMhnA1r33g7uUswLu8JKngDTkCOPMlxJeGFJ78hSQHGZ+/sq/O5KCaQx3wU7+g5lUL2JKBTPlcaY6Ep6VtMQ9rBXCO6ALMxtfiFPKde8Ffj+XMjQzRRcza7llkAakjEn8AFDcZwMXdokwDXa0hafhNQC+oNaD7wedd/M/m2S2Pc66eJcryXSJQ8l3Lpjes+05Y3EjP4rpQ6M+ZS/25CBPK+TkzZC9gnNMRxDxdiLqwj/RhPeBzF3WZs0oDZOPGvsZz6Z/YwOJeF6PW++r9TGWS59l6cNIKPSMOgXC73n3mRbukzPIbP12b5MWze5xTdiAfGTMPgMyTCmeFzchdmhpsHjHTAujTKFByz0fTTy80IyRcHIEB2K6YMpmRhV5qTyecrvy4q6B/vATHPY0j92nVMyVPesPOxKmstr33KOvH8g59SYNeXyIGQKs/7oj7xNIwgk3w2/vYwjHfwfX/ldXOjpNbA9A5MJ/HfwFDFXpgAm2uT1fHMcaCjyWNI+xcDG2rzhFl5gMtwXjx4dv3E85il0xtmZpa4z7SltcsAtzfNFlr+KBgc=

before_install:
  - carthage bootstrap --platform iOS

script:
  - xcodebuild test -scheme "RealmIO-iOS" -destination "platform=iOS Simulator,name=iPhone 7"

after_success:
  - bash <(curl -s https://codecov.io/bash)

